# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e048f77d2908b4825b6a82629849faddf52d23d549b9749e9b611f1888f4665c2bd31dd0b7b08a6c1318e76d03e20a4142edffabd97b6d1b0f3a67492366c0

test:
  secret_key_base: 6cc2686d115fb2cf89324718659a62e473b83b934a9794b26f6ce3c2679b88f2d3e4b2dedd5a82bf00f4b01e3726cecbfab3d2ecc9a65dff995348f4ec9e6d12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
